version: '3.8'

services:

  nats:
    image: nats:latest
    command: -js -DV -m 8222
    ports:
      - 4222:4222
      - 8222:8222

  db:
    image: postgres:latest
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app
    command: 
      - docker-entrypoint.sh
      - postgres
      - -c 
      - 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf

  publisher:
    build: .
    volumes:
      - ./pgwal:/app