listener:
  slotName: myslot_1
  refreshConnection: 30s
  heartbeatInterval: 10s
logger:
  caller: false
  level: info
  humanReadable: true
database:
  host: postgresql
  port: 5432
  name: app
  user: user
  debug: false
  password: pass
  filter:
    tables:
      users:
        - insert
        - update
nats:
  address: nats:4222
  clusterID: test-cluster
  clientID: wal-listener
  topicPrefix: db